### ISSUE TITLE
[BUG] 客户端连接无法通过带有multilogin插件的proxy端的验证

### ISSUE THREAD

**Issue by shinyashen** [CakeDreamer/ProxiedProxy#1]
如题，测试中的entry端和proxy端的multilogin使用了同一个外置登录验证方式，客户端在entry端可以正常连接到下游proxy端，但无法通过proxy端中multilogin插件的验证，提示为“您需要通过 MultiLogin 的验证来进入这个服务器”，导致无法进入proxy端中的子服务器。而不通过entry端连接、直接连接proxy端则可以通过验证。
proxy端与其下属子服务器均启用并正确配置了authlib-injector。

使用的multilogin插件版本为：0.6.1
使用的Velocity版本为：3.2.0-SNAPSHOT(Build #246)

**Comment by ARTI5T** [comment]
不推荐和MultiLogin同时使用，可能存在小概率引起玩家数据错误的风险。
接入联合大厅的ENTRY端不允许使用MultiLogin插件，否则来自Union以外的玩家就可以进入全部的下游服务器。
如果一定要PROXY端使用，请修改PROXY端MultiLogin的config.yml，将`forceUseLogin`设置为`false`。另外，需要将接入Union的皮肤站和Union本身从MultiLogin的皮肤站列表中移除。在此配置文件下，来自Union的玩家只能从ENTRY进入，而正版玩家只能直接连接，原有的Profile绑定将失效，可以解决上述安全问题，但不能避免玩家数据错误。

**Comment by shinyashen** [comment]
其实这边具体问题的话，是联合服在尝试接入联合大厅的过程中产生的问题：联合大厅这边应该是没有安装multilogin只支持Union登入的，而联合服所配置的multilogin支持正版和Union登入，前置的配置工作均已完成，联合服作为下游proxy端其tag已经出现在联合大厅的hub列表中，而我在使用Union账号尝试通过联合大厅进入联合服时却没有通过multilogin的验证，提示为“您需要通过 MultiLogin 的验证来进入这个服务器”。

我的疑惑是，通过该插件进行的客户端连接为什么不能通过配置了其对应皮肤站配置的multilogin的验证（我观察到的现象是：登录会话绕过了multilogin的验证系统从而导致验证不通过）？是否有相应的解决办法？

另外，针对你所说的“来自Union以外的玩家就可以进入全部的下游服务器”这一问题，我认为应当是下游服务器应配备相应的类似于multilogin的验证系统，而这与“客户端通过此插件连接下游velocity时无法通过multilogin验证”这一问题相关性不是很大。

**Comment by ARTI5T** [comment]
Multilogin检测的是连接服务器时协商加密的数据包。在ENTRY和PROXY之间的连接是离线模式的，而离线模式的数据是不加密的，因此连接服务器时不会协商加密，进而不会被Multilogin检测到。
想要让新加入的玩家被Multilogin检测到，那么就需要使得ENTRY和PROXY之间的连接处于在线模式。但是Velocity不支持向后端服务器发送加密的数据包，因此这种方法不行。
联合大厅的架构仍然是基于一般的代理-子服架构，由代理负责对用户的认证。下游服务器对玩家进行认证并不是一个普遍的做法。

**Comment by shinyashen** [comment]
了解了，谢谢解惑！
