### ISSUE TITLE
存在重放攻击风险

### ISSUE THREAD

**Issue by ksqeib** [CakeDreamer/ProxiedProxy#2]
在work.art1st.proxiedproxy.ProxiedProxy中有一段代码
ForwardingParser parser = new Gson().fromJson(response, ForwardingParser.class);
                        if (!parser.isTrusted(proxyConfig.trustedEntries)) {
                            loginInboundConnection.disconnect(Component.text("You are connecting from an untrusted entry."));
                            return;
                        }

此段代码中调用的`isTrusted`方法存在被重放攻击的风险

理由是 该方法中未对方法`getSignBody`返回的数据合法性进行校验
如果发生重放 一定会成功通过校验

**Comment by ARTI5T** [comment]
`getSignBody`方法获取的`remoteAddress`是从连接中获取的远程IP，重放攻击无法伪造IP，除非连接就是来自可信的entry。但此处确实存在一些bug，没有验证时间戳；没有验证`entryId`是否合法。[commit aca9e73](https://github.com/CakeDreamer/ProxiedProxy/commit/aca9e73e5a200eb9e6e36203bbac8e676d4f5267) 修复了上述两个问题。

**Comment by ksqeib** [comment]
`remoteAddress`中的地址也是来源于对端发送的json序列化，并非不可伪造。如果不对其进行验证，`remoteAddress`也仅仅是对端发送的信息而已。

**Comment by ARTI5T** [comment]
你说得对。[72a332e](https://github.com/CakeDreamer/ProxiedProxy/commit/72a332eea01ad6f6c52b6b59fd8e7369a92b4a06)
